package com.bidops.domain.project.enums;

public enum ActivityType {
    // 문서
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    // 분석
    ANALYSIS_STARTED,
    ANALYSIS_COMPLETED,
    ANALYSIS_FAILED,
    // 요구사항
    REQUIREMENT_UPDATED,
    REQUIREMENT_REVIEW_CHANGED,
    REQUIREMENT_INSIGHT_UPDATED,
    REQUIREMENT_INSIGHT_REANALYZED,
    // 체크리스트
    CHECKLIST_CREATED,
    CHECKLIST_ITEM_CREATED,
    CHECKLIST_ITEM_UPDATED,
    CHECKLIST_ITEM_STATUS_CHANGED,
    // 질의
    INQUIRY_CREATED,
    INQUIRY_UPDATED,
    INQUIRY_STATUS_CHANGED,
    // 멤버
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    // 산출물
    ARTIFACT_CREATED,
    ARTIFACT_UPDATED,
    ARTIFACT_DELETED,
    ARTIFACT_STATUS_CHANGED,
    ARTIFACT_VERSION_UPLOADED,
    // 프로젝트
    PROJECT_CREATED,
    PROJECT_UPDATED
}
